projectsyn/modulesync-control

Makefile
config_defaults.yml
moduleroot/.editorconfig.erb
moduleroot/.github/ISSUE_TEMPLATE/01_bug_report.md.erb
moduleroot/.github/ISSUE_TEMPLATE/02_feature_request.md.erb
moduleroot/.github/ISSUE_TEMPLATE/config.yml.erb
moduleroot/.github/PULL_REQUEST_TEMPLATE.md.erb
moduleroot/.github/changelog-configuration.json.erb
moduleroot/.github/workflows/release.yaml.erb
moduleroot/.github/workflows/test.yaml.erb
moduleroot/.gitignore.erb
moduleroot/.yamllint.yml.erb
moduleroot/CODE_OF_CONDUCT.md.erb
moduleroot/CONTRIBUTING.md.erb
moduleroot/LICENSE.erb
moduleroot/Makefile.erb
moduleroot/Makefile.vars.mk.erb
moduleroot/docs/antora.yml.erb
moduleroot/renovate.json.erb

Adds an initial version of the scaffolding template

Add Commodore component template

---

managed_modules.yml
moduleroot/.github/workflows/release.yaml.erb
moduleroot/.github/workflows/test.yaml.erb
moduleroot/CONTRIBUTING.md.erb
moduleroot/Makefile.erb
moduleroot/Makefile.vars.mk.erb

* Adds the first component to managed_modules
Related PRs:
* https://github.com/projectsyn/component-keycloak/pull/26
* https://github.com/projectsyn/commodore/pull/335/

Add component-keycloak to managed modules

---

config_defaults.yml
moduleroot/CONTRIBUTING.md.erb

* Generate Github PR URL from available modulesync metadata
* Remove `CHANGELOG.md`, if it exists in the component

Template improvements

---

managed_modules.yml

This PR onboards <https://github.com/projectsyn/component-cert-manager>.

Onboard `component-cert-manager`

---

managed_modules.yml

Onboard component appuio/openshift4-logging

---

managed_modules.yml

Onboard component cluster-autoscaler

---

managed_modules.yml

Onboard `component-backup-k8up`

---

managed_modules.yml

Onboard component external-dns

---

managed_modules.yml

Onboard component azuredisk-csi-driver

---

moduleroot/Makefile.erb

Add `go test` statement to Makefile if `feature_goUnitTests` is enabled

---

managed_modules.yml

Onboard component acme-dns

---

managed_modules.yml

Onboard appuio/component-openshift4-authentication

---

managed_modules.yml

Onboard component openshift4-ingress

---

managed_modules.yml

Onboard group sync operator

---

managed_modules.yml

Onboard component adhoc-configurations

---

moduleroot/.editorconfig.erb

Remove nonsensical comment referencing Makefiles

---

managed_modules.yml

Onboard component openshift4-registry

---

managed_modules.yml

See commits for onboarded components

Onboard components

---

Makefile

Adds a switch in the control-repo Makefile to support sync noop's with Podman.
This change doesn't get rolled out to managed modules.

Add support for Podman

---

managed_modules.yml

Add crossplane component

---

managed_modules.yml

Add appcat-service-postgresql component
