- .github/workflows/sync.yml
- README.adoc
Allows to trigger the sync via Dispatch. On GitHub WebUI, that would in https://github.com/projectsyn/modulesync-control/actions/workflows/sync.yml. Optionally, it accepts a filter where the sync would only sync the repository(s) matching the regex.
> Support triggering sync from Dispatch

- moduleroot/Makefile.vars.mk.erb
Now we ignore `./helmcharts/*`, `./manifests/*` and `./vendor/*` when linting YAML files.
> Add more directories to ignore when linting YAML files

- .github/PULL_REQUEST_TEMPLATE.md
- .github/changelog-configuration.json
- .github/workflows/release.yaml
* Adds a PR template that reminds authors to also update the component template when doing changes. We may come up with something better in the future.
* Adds a release workflow triggered by git tags that generates changelog and a release. We may not have a use for this yet, but maybe later we may start tagging template versions with changelogs (e.g. parameter changes)
> Update PR template, add release workflow

- moduleroot/Makefile.erb
See also / same as projectsyn/commodore/pull/349.
Currently the `parameters.kapitan.dependencies.[].output_path` needs to be overridden for all dependencies in test compiles (`make test`).
See:
- https://github.com/projectsyn/component-cert-manager/blob/master/tests/defaults.yml#L9
- https://github.com/projectsyn/component-keycloak/blob/master/tests/builtin.yml#L10
- https://github.com/projectsyn/component-keycloak/blob/master/tests/external.yml#L10
This is not optimal. It can lead to errors if a developer forgets to update the `tests/` file. The "real" output can now differ from the test output. Additionally it won't scale for components like [`component-argocd`](https://github.com/projectsyn/component-argocd/blob/master/class/argocd.yml) where there are many dependecies.
This PR adds …
> Add local dependencies search path in commodore test compile

- moduleroot/.editorconfig.erb
See: https://github.com/projectsyn/commodore/pull/360
`jsonnetfmt` already has a very opinionated formatter, which makes the linter superfluous and can lead to conflicts between `jsonnetfmt` and `editorconfig` linters.
See: https://github.com/projectsyn/component-backup-k8up/pull/36/checks?check_run_id=3221663321#step:3:10
> Exclude jsonnet files from indent linter

- moduleroot/.yamllint.yml.erb
- moduleroot/Makefile.erb
- moduleroot/Makefile.vars.mk.erb
`find` works differently on GNU and BSD.
BSD find would need an `-E` option or have the backslash before the braces removed.
> Make yamllint exludes work on both BSD and GNU

- moduleroot/Makefile.erb
- moduleroot/Makefile.vars.mk.erb
When compiling a component which makes use of its own component library, we need to add the component directory to the search paths for `commodore component compile`.
This commit sets the default value of variable `commodore_args` to
```
--search-paths ./dependencies --search-paths .
````
This variable is used by all compile targets, and some targets now append `-f tests/$(instance).yml` to the variable instead of setting the variable from scratch.
Matching commodore PR: https://github.com/projectsyn/commodore/pull/368
> Update compile make targets to support components with library

- config_defaults.yml
- moduleroot/.github/workflows/test.yaml.erb
See https://github.com/appuio/component-group-sync-operator/pull/6
> Enable matrix operations on goldenTests

- .github/PULL_REQUEST_TEMPLATE.md
- moduleroot/.github/PULL_REQUEST_TEMPLATE.md.erb
Related PR in commodore: https://github.com/projectsyn/commodore/pull/382
> Update PR template

- moduleroot/Makefile.erb
If there are components that have matrix builds/instances, switching between instances could include undesired compiled artifacts. Thus we clean it before
(e.g. `make gen-golden -e instance=builtin` then `make gen-golden -e instance=external` `tests/golden/external` would also include the `builtin` files)
Commodore template update integrated in PR: https://github.com/projectsyn/commodore/pull/382
> Clean compiled artifacts before generating golden files

- moduleroot/renovate.json.erb
* Disable Renovate dependency dashboard for all components
* See also https://github.com/projectsyn/commodore/pull/387
> Disable Renovate dashboard

- moduleroot/Makefile.vars.mk.erb
On non-Docker systems, docker.io may not be the default registry.
Avoid misconfiguration and incompatibilities by explicitly defining the
registry when pulling images.
> Use absolute Container Image URLs

- moduleroot/Makefile.vars.mk.erb
By default the GID defined in commodore's Dockerfile is used,
which may
or may not match an existing user on the system.
This commit explicitly sets the group ID when starting
containers.
> Ensure files are generated with the correct GID

- moduleroot/Makefile.erb
- moduleroot/Makefile.vars.mk.erb
This fixes the issues introduced by #54 in `make test` for components which try to download a Helm chart. With the GID change for the container in #54, Commodore can't download files to `/app` anymore (the default home directory of the container), since that directory is owned by root.
This commit ensures that the Commodore container has a writable home directory by explicitly setting `HOME` to the component source directory.
See https://github.com/projectsyn/component-azuredisk-csi-driver/pull/26 for an example where the change breaks `make test`.
> Explicitly set `HOME` environment variable for Commodore container

- moduleroot/Makefile.vars.mk.erb
The make target is still called `docs-serve`.
This PR:
* Bumps Antora preview command docker image to vshn/antora-preview:3.0.0.1.   This gives us a Antora preview which auto-refreshes the docs while the command is running and updates the image to one which contains the current VSHN Kroki instance URL.
* Only mounts `<component-dir>/docs` and `<component-dir>/.git` into the Docker container. This should avoid issues with Antora getting confused about paths in `vendor` not being readable in the container.
* Exposes port 35729 of the Docker container for the auto-reload browser plugin.
> Adjust the Antora docs preview command

- moduleroot/Makefile.vars.mk.erb
The new Antora image uses `/preview/antora` instead of `/antora`
Already adjusted in https://github.com/projectsyn/commodore/pull/408
> Fix volume paths for Antora preview command

- moduleroot/Makefile.vars.mk.erb
The Commodore template has already been updated in https://github.com/projectsyn/commodore/pull/423
> Update Antora preview image to 3.0.1.1

- config_defaults.yml
- moduleroot/.github/workflows/test.yaml.erb
- moduleroot/Makefile.erb
- moduleroot/Makefile.vars.mk.erb
- moduleroot/renovate.json.erb
Until now, the test matrix has been defined in a local variable for the `.github/workflows/test.yaml` template. To allow us to generate Renovate `postUpgradeTasks` and a list of test instances in a make variable, we need to be able to access the matrix test configuration in other templates.
This PR moves the test matrix configuration to global variable `testMatrix`. For now, the GitHub actions template will continue to read the test matrix from the file-level variable `matrix`, but will fall back to the global variable `testMatrix` if the file-level variable is missing.
Additionally, the PR adds new make targets `golden-diff-all` and `gen-golden-all`. These targets use a static list of test instances in make variable `test_instances`. The contents of this variable are generated from the …
> Add logic to generate Renovate `postUpgradeTasks`

- .github/workflows/sync.yml
This should fix the modulesync errors that are popping up for recent runs, e.g. https://github.com/projectsyn/modulesync-control/runs/5630431030?check_suite_focus=true
See the modulesync issue at https://github.com/voxpupuli/modulesync/issues/250
> Explicitly set `GITHUB_BASE_URL` for modulesync

- moduleroot/.github/workflows/release.yaml.erb
- moduleroot/.github/workflows/test.yaml.erb
Already updated in Commodore template in https://github.com/projectsyn/commodore/pull/420
> Update `actions/checkout` to v3 in component template

- moduleroot/.github/workflows/test.yaml.erb
Note: Go tests for components are not part of the Commodore component template.
> Update GitHub actions `setup-go` and `cache` to v3 in template

- config_defaults.yml
- moduleroot/.github/workflows/test.yaml.erb
All onboarded components have been migrated to the new global parameter `testMatrix`.
Follow-up to #62 
> Remove support for old `matrix` parameter in GitHub actions template

- moduleroot/Makefile.vars.mk.erb
While it was already possible to use podman by setting the DOCKER_CMD
env var, this was not enough for most commands.
This commit adds support for Podman out of the box. If Docker is
installed, it will be preferred over Podman to stay
backwards-compatible.
The `--userns=keep-id` flag is required on Podman to ensure that 1.) the
process in the container can write to the mounted workdirs, and 2.)
ensure files created by processes in the container have the correct
owner
and group IDs: The ones from the user running the Make tasks.
> Support Podman out of the box

- moduleroot/Makefile.erb
- moduleroot/Makefile.vars.mk.erb
We want to be able to adjust which `commodore` to use without having to reproduce the full compile command when compiling individual components with `make test`, `make golden-diff` or `make gen-golden`.
This commit reduces `COMMODORE_CMD` to be the equivalent of a bare invocation of `commodore` and introduces a new variable `COMPILE_COMMAND` which corresponds to the previous value of `COMMODORE_CMD`.
Matching component-template PR: https://github.com/projectsyn/commodore/pull/437
> Split `COMMODORE_CMD` and `COMPILE_CMD`

- managed_modules.yml
Since AKS Kubernetes 1.21 the CSI driver is installed
via server side apply ba Azure itself.
No need anymore for this component.
> Remove component-azuredisk-csi-driver

- managed_modules.yml
Currently the component is not in use.
> Remove external-dns

- moduleroot/.github/workflows/release.yaml.erb
> Bump release-changelog-builder-action to v3 in template

- moduleroot/README.md.erb
- moduleroot/docs/antora.yml.erb
This PR adds a template for the component README.md.
Addititionally, the PR also changes how the contents of `docs/antora.yml` are managed: we no longer need the parameters `name` and `title` for `docs/antora.yml` in the components' `.sync.yml`, instead we construct the component name ("slug" in the cookiecutter component template) from the GitHub repo name, and use `:global.componentName` as the component title ("name" in the cookiecutter template).
Commodore PR: https://github.com/projectsyn/commodore/pull/529
> Manage component README

- moduleroot/.gitignore.erb
With the new rooted gitignore entries, we need to add `/dependencies` as `component compile` generates that directory for most components.
Follow-up to #79
Commodore PR: https://github.com/projectsyn/commodore/pull/533
> Add `/dependencies` to component `.gitignore`

- moduleroot/Makefile.erb
- moduleroot/Makefile.vars.mk.erb
The `lint_kubent` target runs `kubent` on a single golden test instance, defaulting to instance `defaults`. The commit also adds a target `lint_kubent_all` which will run `kubent` for all targets separately.
We don't run `kubent` over all golden tests simultaneously because the tool doesn't support linting multiple Kubernetes objects with the same name and namespace in a single run.
The commit ensures that the `kubent` lint targets are only added for components which are configured with golden tests enabled.
Commodore PR: https://github.com/projectsyn/commodore/pull/544
Resolves #47 
> Add `lint_kubent` make targets to check for deprecated API versions

- moduleroot/Makefile.vars.mk.erb
Update `Makefile.vars.mk` to support both regular Git checkouts and Git worktree checkouts using a OS-agnostic `.git` symlink.
> Add logic in `Makefile.vars.mk` to handle Git worktree checkouts

- moduleroot/Makefile.vars.mk.erb
This should reduce the amount of patching required when setting up a component in a subdirectory from the template.
Commodore PR: https://github.com/projectsyn/commodore/pull/588
> Hard-code component name in `Makefile.vars.mk`

- moduleroot/.cruft.json.erb
Add a `.cruft.json` to all managed components, so we can migrate component template sync to `commodore component sync` based on the Cookiecutter template in https://github.com/projectsyn/commodore-component-template/
> Add template for `.cruft.json`
